#!/bin/bash

# Setze die SSH-Anmeldeinformationen
SRVIp="IP"
User="username"
Password="pwd"

# Setze die Pfade
mail_path="Directory Location"
target_path="Directory Locatio"

# Führe die SSH-Verbindung und das Kopieren der Log-Dateien durch
sshpass -p "$pwd" ssh $pi@$sinthu "scp $path/* $user@rtaret"

 
sudo apt-get install sshpass
